theme = "solarized-dark"
icons = "awesome"


[[block]]
block = "music"
max_width = 21
marquee = false
player = "spotify"
buttons = ["play", "next"]

# [[block]]
# block = "temperature"

# [[block]]
# block = "load"
# interval = 1
# format = "{1m} {5m} {15m}"

# [[block]]
# block = "cpu"
# interval = 0.7

# [[block]]
# block = "uptime"

[[block]]
block = "memory"
interval = 5
info_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 30.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/home/harry"
alias = "~"
info_type = "available"
unit = "GB"
interval = 20
warning = 120

[[block]]
block = "net"
device = "wlp58s0"
ssid = true
ip = true
bitrate = false
speed_up = false
speed_down = false
interval = 5

[[block]]
block = "sound"

[[block]]
block = "battery"

[[block]]
block = "backlight"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
